#!/usr/bin/env python3
"""Generate user-guide-hi from user-guide-fr template with Hindi (Devanagari) copy."""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FR = ROOT / "videos" / "user-guide-fr" / "index.html"
OUT = ROOT / "videos" / "user-guide-hi" / "index.html"

REPLACEMENTS = [
    ('<html lang="fr">', '<html lang="hi">'),
    ('<title>Guide utilisateur complet - PocketBudJet | JosspaTech</title>',
     '<title>पूर्ण उपयोगकर्ता गाइड - PocketBudJet | JosspaTech</title>'),
    ('<li><a href="/">Accueil</a></li>', '<li><a href="/">होम</a></li>'),
    ('<li><a href="/#products">Produits</a></li>', '<li><a href="/#products">उत्पाद</a></li>'),
    ('<li><a href="/how-to/">Guides</a></li>', '<li><a href="/how-to/">गाइड</a></li>'),
    ('<li><a href="#" class="cta-button">Télécharger</a></li>', '<li><a href="#" class="cta-button">डाउनलोड</a></li>'),
    ('<a href="/">Accueil</a>', '<a href="/">होम</a>'),
    ('<a href="/how-to/">Guides</a>', '<a href="/how-to/">गाइड</a>'),
    ('<span class="current">Guide utilisateur</span>', '<span class="current">उपयोगकर्ता गाइड</span>'),
    ('<h1>Le guide complet PocketBudJet</h1>', '<h1>पूर्ण PocketBudJet गाइड</h1>'),
    ('<p class="subheader">Chaque écran. Chaque fonction. Chaque réglage. Une visite visuelle de tout ce que PocketBudJet peut faire pour vos finances — pour les communautés francophones aux États-Unis.</p>',
     '<p class="subheader">हर स्क्रीन। हर फ़ीचर। हर सेटिंग। PocketBudJet आपके वित्त के लिए क्या कर सकता है — संयुक्त राज्य अमेरिका में हिंदी बोलने वाले समुदायों के लिए एक दृश्य टूर।</p>'),
    ('<h2>Regardez la visite complète</h2>', '<h2>पूर्ण टूर देखें</h2>'),
    ('<p class="section-sub">Écrans réels, impulsion dorée là où appuyer, narration pas à pas.</p>',
     '<p class="section-sub">असली स्क्रीन, सुन्‍हरा पल्स जहाँ टैप करें, कदम-दर-कदम कथन।</p>'),
    ('<div class="tap-to-start-label">Appuyez pour lire</div>',
     '<div class="tap-to-start-label">चलाने के लिए टैप करें</div>'),
    ('<span class="narration-step-badge">Diapositive ', '<span class="narration-step-badge">स्लाइड '),
    (' sur 28</span>', ' में से 28</span>'),
    ('<h3>Bienvenue et configuration</h3>', '<h3>स्वागत और सेटअप</h3>'),
    ('<p>Téléchargez PocketBudJet, suivez l\'assistant de configuration, créez votre premier compte et démarrez votre essai Premium de 15 jours — sans carte bancaire. Après l\'essai, abonnez-vous mensuellement ou annuellement pour conserver l\'accès. L\'assistant vous guide pour votre nom, votre devise, vos comptes, vos revenus (salaire brut et net), vos factures, vos objectifs et votre style de budget — tout ce dont l\'application a besoin pour être intelligente dès le premier jour.</p>',
     '<p>PocketBudJet डाउनलोड करें, सेटअप विज़ार्ड का पालन करें, अपना पहला खाता बनाएँ और 21-दिन का Premium ट्रायल शुरू करें — बिना कार्ड के। ट्रायल के बाद, पहुँच बनाए रखने के लिए मासिक या वार्षिक सदस्यता लें। विज़ार्ड आपका नाम, मुद्रा, खाते, आय (सकल और शुद्ध वेतन), बिल, लक्ष्य और बजट शैली कवर करता है — ऐप को पहले दिन से स्मार्ट बनाने के लिए जो कुछ भी चाहिए।</p>'),
    ('<h3>Votre tableau de bord</h3>', '<h3>आपका डैशबोर्ड</h3>'),
    ('<p>Des cartes revenus, dépenses et solde en haut. L\'indicateur de rythme de dépenses montre si vous êtes dans les clous. Des widgets pour les actions rapides. Les alertes d\'anomalies signalent les transactions inhabituelles. L\'indicateur compare où vous en êtes par rapport à où vous devriez être à ce stade du mois.</p>',
     '<p>ऊपर आय, खर्च और शेष कार्ड। खर्च की गति संकेतक दिखाता है कि आप ट्रैक पर हैं या नहीं। त्वरित कार्यों के लिए विजेट। असामान्य लेनदेन के लिए विसंगति अलर्ट। संकेतक तुलना करता है कि महीने के इस चरण में आप कहाँ हैं बनाम कहाँ होने चाहिए।</p>'),
    ('<h3>Ajouter des transactions</h3>', '<h3>लेनदेन जोड़ें</h3>'),
    ('<p>Appuyez sur +, saisissez le montant, choisissez une catégorie — c\'est fait. Répartissez les transactions sur plusieurs catégories. Ajoutez des pièces jointes comme des photos de reçus. Utilisez des modèles pour les entrées récurrentes. Un conseil : écrivez les noms des commerçants de la même façon à chaque fois — « Daily Grind », pas « DAILY GRIND » ou « Daily Grind Coffee » — pour qu\'ils se regroupent correctement dans les rapports.</p>',
     '<p>+ टैप करें, राशि दर्ज करें, श्रेणी चुनें — हो गया। लेनदेन को कई श्रेणियों में बाँटें। रसीद की तस्वीरें जैसे अटैचमेंट जोड़ें। आवर्ती प्रविष्टियों के लिए टेम्पलेट उपयोग करें। सुझाव: व्यापारी नाम हर बार एक जैसे लिखें — «Daily Grind», «DAILY GRIND» या «Daily Grind Coffee» नहीं — ताकि रिपोर्ट में सही समूह बनें।</p>'),
    ('<h3>Importer des données</h3>', '<h3>डेटा आयात करें</h3>'),
    ('<p>Importez des relevés bancaires CSV, OFX, QFX, QIF, XLSX ou PDF — aucune connexion bancaire requise. Le Smart Mapper détecte automatiquement les colonnes. La détection des doublons évite les comptages en double. Importez au moins trois mois d\'historique — plus de données signifie une IA plus intelligente et de meilleurs rapports. La synchronisation bancaire automatique (États-Unis uniquement, via Teller) est optionnelle avec Premium payant — pas pendant l\'essai de 15 jours. Pour les instructions pas à pas, consultez notre <a href="/videos/import/" style="color: #1A4F7A; font-weight: 600; text-decoration: underline;">vidéo d\'import de données bancaires</a>.</p>',
     '<p>बैंक स्टेटमेंट CSV, OFX, QFX, QIF, XLSX या PDF आयात करें — बैंक लॉगिन की ज़रूरत नहीं। Smart Mapper स्वचालित रूप से कॉलम पहचानता है। डुप्लिकेट पहचान दोहरी गिनती रोकती है। कम से कम तीन महीने का इतिहास आयात करें — अधिक डेटा का मतलब स्मार्ट AI और बेहतर रिपोर्ट। स्वचालित बैंक सिंक (केवल अमेरिका, Teller के माध्यम से) सशुल्क Premium के साथ वैकल्पिक है — 21-दिन के ट्रायल के दौरान नहीं। चरण-दर-चरण निर्देशों के लिए हमारा <a href="/videos/import/" style="color: #1A4F7A; font-weight: 600; text-decoration: underline;">बैंक डेटा आयात वीडियो</a> देखें।</p>'),
    ('<h3>Numériser des documents</h3>', '<h3>दस्तावेज़ स्कैन करें</h3>'),
    ('<p>Scannez les reçus avec votre appareil photo. L\'OCR lit le commerçant, le montant et la date. La prise en charge du scanner WiFi se connecte à votre scanner ADF domestique pour le traitement par lots. Lit même l\'écriture manuscrite. À notre connaissance, PocketBudJet est la seule application de budget avec prise en charge du scanner WiFi. Placez une pile de reçus dans le bac de votre scanner et laissez faire.</p>',
     '<p>अपने कैमरे से रसीदें स्कैन करें। OCR व्यापारी, राशि और तारीख पढ़ता है। WiFi स्कैनर समर्थन आपके घरेलू ADF स्कैनर से बैच प्रोसेसिंग के लिए जुड़ता है। हस्तलिखित भी पढ़ता है। हमारी जानकारी में PocketBudJet WiFi स्कैनर समर्थन वाला एकमात्र बजट ऐप है। रसीदों का ढेर स्कैनर ट्रे में रखें और होने दें।</p>'),
    ('<h3>Gérer les budgets</h3>', '<h3>बजट प्रबंधित करें</h3>'),
    ('<p>Cinq modèles de budget ou créez le vôtre. Limites par catégorie avec barres de progression codées par couleur. Reportez le budget non utilisé. La vue d\'ensemble de santé montre votre position globale. Les rapports d\'écarts comparent le prévu et le réel.</p>',
     '<p>पाँच बजट टेम्पलेट या अपना बनाएँ। रंग-कोडित प्रगति बार के साथ श्रेणी सीमाएँ। अप्रयुक्त बजट आगे बढ़ाएँ। स्वास्थ्य अवलोकन आपकी समग्र स्थिति दिखाता है। विचलन रिपोर्ट योजना बनाम वास्तविक की तुलना करती हैं।</p>'),
    ('<h3>Factures et transactions récurrentes</h3>', '<h3>बिल और आवर्ती लेनदेन</h3>'),
    ('<p>Calendrier visuel des factures avec dates d\'échéance. Les points verts marquent les jours de paie. Configurez les revenus et dépenses récurrents. La prédiction intelligente estime les factures à venir selon vos habitudes.</p>',
     '<p>नियत तारीखों के साथ दृश्य बिल कैलेंडर। हरे बिंदु वेतन दिन चिह्नित करते हैं। आवर्ती आय और खर्च सेट करें। स्मार्ट भविष्यवाणी आपकी आदतों के आधार पर आगामी बिल अनुमानित करती है।</p>'),
    ('<h3>Épargne et objectifs</h3>', '<h3>बचत और लक्ष्य</h3>'),
    ('<p>Définissez des objectifs d\'épargne avec dates cibles. Créez des fonds de réserve pour les dépenses planifiées. Une liste de souhaits avec période de réflexion de 30 jours pour freiner les achats impulsifs. Le calculateur « et si » montre les compromis. La période de 30 jours est un rappel — ajoutez quelque chose que vous voulez acheter, et PBJ attend 30 jours avant de le compter. Vous seriez surpris du nombre de « indispensables » qui ne survivent pas à l\'attente.</p>',
     '<p>लक्ष्य तिथियों के साथ बचत लक्ष्य निर्धारित करें। नियोजित खर्चों के लिए सिंक फंड बनाएँ। आवेग खरीदारी रोकने के लिए 30-दिन की विचार अवधि वाली इच्छा सूची। «क्या हो अगर» कैलकुलेटर समझौते दिखाता है। 30-दिन की अवधि एक अनुस्मारक है — जो खरीदना चाहते हैं जोड़ें, PBJ गिनने से पहले 30 दिन प्रतीक्षा करता है।</p>'),
    ('<h3>Réduire les dettes</h3>', '<h3>कर्ज़ कम करें</h3>'),
    ('<p>Suivez toutes vos dettes au même endroit. Choisissez l\'avalanche (taux le plus élevé en premier) ou la boule de neige (solde le plus petit en premier). Voyez votre date de libération de dettes. Les scénarios « et si » montrent comment des paiements supplémentaires accélèrent le remboursement. Connaître votre date exacte de libération change tout. Cela transforme une montagne de dettes en compte à rebours.</p>',
     '<p>सभी कर्ज़ एक जगह ट्रैक करें। एवलांच (सबसे ऊँची दर पहले) या स्नोबॉल (सबसे छोटा शेष पहले) चुनें। अपनी कर्ज़-मुक्ति तिथि देखें। «क्या हो अगर» परिदृश्य दिखाते हैं कि अतिरिक्त भुगतान चुकौती कैसे तेज़ करते हैं। सटीक मुक्ति तिथि जानना सब बदल देता है।</p>'),
    ('<h3>Investissements et patrimoine net</h3>', '<h3>निवेश और कुल संपत्ति</h3>'),
    ('<p>Suivez les actions, la crypto (19 monnaies prises en charge) et la valeur immobilière via les estimations Zillow. Surveillez votre score de crédit. Consultez les polices d\'assurance aux côtés de vos actifs pour une vue complète de votre patrimoine net.</p>',
     '<p>स्टॉक, क्रिप्टो (19 मुद्राएँ समर्थित) और Zillow अनुमानों के माध्यम से संपत्ति मूल्य ट्रैक करें। अपना क्रेडिट स्कोर मॉनिटर करें। कुल संपत्ति के पूर्ण दृश्य के लिए संपत्तियों के साथ बीमा पॉलिसी देखें।</p>'),
    ('<h3>Rapports et analyses</h3>', '<h3>रिपोर्ट और विश्लेषण</h3>'),
    ('<p>Plus de 10 types de rapports : dépenses par catégorie, revenus contre dépenses, comparaisons d\'une année sur l\'autre, tableau de bord des anomalies, tendance du patrimoine net et rapports personnalisés que vous concevez vous-même.</p>',
     '<p>10 से अधिक रिपोर्ट प्रकार: श्रेणी के अनुसार खर्च, आय बनाम खर्च, वर्ष-दर-वर्ष तुलना, विसंगति डैशबोर्ड, कुल संपत्ति रुझान और आपके द्वारा डिज़ाइन की गई कस्टम रिपोर्ट।</p>'),
    ('<h3>Coach financier IA</h3>', '<h3>AI वित्त कोच</h3>'),
    ('<p>Des analyses personnalisées basées sur vos habitudes de dépenses. Sur inscription uniquement. Repère les tendances que vous manqueriez, avertit des activités inhabituelles et envoie un récapitulatif financier hebdomadaire. Plus vous lui donnez de données, plus il devient intelligent. Importez quelques mois d\'historique et l\'IA a de vrais modèles à analyser.</p>',
     '<p>आपकी खर्च आदतों पर आधारित व्यक्तिगत अंतर्दृष्टि। केवल ऑप्ट-इन पर। रुझान पकड़ता है जो आप चूक सकते हैं, असामान्य गतिविधि की चेतावनी देता है और साप्ताहिक वित्त सारांश भेजता है। जितना अधिक डेटा, उतना स्मार्ट।</p>'),
    ('<h3>Assistant IA</h3>', '<h3>AI सहायक</h3>'),
    ('<p>Posez des questions sur votre argent en langage courant. « Combien ai-je dépensé en restaurants le mois dernier ? » ou « Suis-je au-dessus du budget ? » Onze types de requêtes, toutes traitées sur votre appareil.</p>',
     '<p>सामान्य भाषा में अपने पैसे के बारे में प्रश्न पूछें। «पिछले महीने रेस्तरां में कितना खर्च किया?» या «क्या मैं बजट से ऊपर हूँ?» ग्यारह क्वेरी प्रकार, सभी आपके डिवाइस पर संसाधित।</p>'),
    ('<h3>Trouver n\'importe quelle fonction instantanément</h3>', '<h3>कोई भी फ़ीचर तुरंत खोजें</h3>'),
    ('<h3>Export et partage</h3>', '<h3>निर्यात और साझा करें</h3>'),
    ('<p>Exportez en six formats : CSV, XLSX, OFX, PDF, JSON et sauvegarde chiffrée. Générez un rapport prêt pour votre comptable. Lancez un serveur LAN pour transférer des fichiers vers votre ordinateur.</p>',
     '<p>छह प्रारूपों में निर्यात: CSV, XLSX, OFX, PDF, JSON और एन्क्रिप्टेड बैकअप। अपने लेखाकार के लिए तैयार रिपोर्ट बनाएँ। अपने कंप्यूटर पर फ़ाइलें स्थानांतरित करने के लिए LAN सर्वर शुरू करें।</p>'),
    ('<h3>Tableau de bord Web PC</h3>', '<h3>PC वेब डैशबोर्ड</h3>'),
    ('<p>Accédez à PocketBudJet depuis n\'importe quel navigateur sur votre réseau local. Scannez le code QR pour coupler. Cinq onglets : Tableau de bord, Transactions, Budgets, Rapports, Réglages. Création, modification et suppression complètes. Synchronisation en temps réel avec votre téléphone. Idéal pour importer les fichiers bancaires téléchargés sur votre ordinateur — glissez-déposez directement dans le navigateur.</p>',
     '<p>अपने स्थानीय नेटवर्क पर किसी भी ब्राउज़र से PocketBudJet एक्सेस करें। जोड़ने के लिए QR कोड स्कैन करें। पाँच टैब: डैशबोर्ड, लेनदेन, बजट, रिपोर्ट, सेटिंग्स। पूर्ण बनाएँ, संपादित करें, हटाएँ। फ़ोन के साथ रीयल-टाइम सिंक। कंप्यूटर पर डाउनलोड की गई बैंक फ़ाइलें आयात करने के लिए आदर्श — सीधे ब्राउज़र में ड्रैग-एंड-ड्रॉप करें।</p>'),
    ('<h3>Flexibilité d\'import</h3>', '<h3>आयात लचीलापन</h3>'),
    ('<p>Importez depuis des relevés CSV, OFX, QIF et PDF — sans connexion bancaire. Numérisez les reçus papier avec votre appareil photo. Transférez les reçus électroniques depuis votre courriel. Glissez-déposez des fichiers dans le tableau de bord PC. Chaque import se catégorise automatiquement selon vos règles. La synchronisation bancaire (États-Unis uniquement) reste optionnelle avec Premium payant.</p>',
     '<p>CSV, OFX, QIF और PDF स्टेटमेंट से आयात — बैंक कनेक्शन के बिना। कैमरे से कागज़ी रसीदें स्कैन करें। ईमेल से डिजिटल रसीदें स्थानांतरित करें। PC डैशबोर्ड में फ़ाइलें ड्रैग-एंड-ड्रॉप करें। प्रत्येक आयात आपके नियमों के अनुसार स्वचालित रूप से श्रेणीबद्ध होता है। बैंक सिंक (केवल अमेरिका) सशुल्क Premium के साथ वैकल्पिक रहता है।</p>'),
    ('<h3>Synchronisation familiale</h3>', '<h3>पारिवारिक सिंक</h3>'),
    ('<p>Synchronisez avec les membres de la famille via WiFi ou Bluetooth — sans Internet. Couplez avec un code QR. Budgets communs avec visibilité individuelle des dépenses. Résolution automatique des conflits pour les modifications simultanées.</p>',
     '<p>WiFi या Bluetooth के माध्यम से परिवार के सदस्यों के साथ सिंक — इंटरनेट के बिना। QR कोड से जोड़ें। व्यक्तिगत खर्च दृश्यता के साथ साझा बजट। एक साथ संपादन के लिए स्वचालित संघर्ष समाधान।</p>'),
    ('<h3>Vue calendrier</h3>', '<h3>कैलेंडर दृश्य</h3>'),
    ('<p>Calendrier mensuel avec des points de transaction chaque jour. Dates d\'échéance des factures et marqueurs de jour de paie. Codé par couleur selon la catégorie. Appuyez sur n\'importe quel jour pour voir les transactions de ce jour.</p>',
     '<p>प्रत्येक दिन लेनदेन बिंदुओं के साथ मासिक कैलेंडर। बिल नियत तारीखें और वेतन दिन मार्कर। श्रेणी के अनुसार रंग-कोडित। उस दिन के लेनदेन देखने के लिए किसी भी दिन टैप करें।</p>'),
    ('<h3>Favoris et règles</h3>', '<h3>पसंदीदा और नियम</h3>'),
    ('<p>Marquez les transactions importantes pour un accès rapide. Créez des règles de catégorisation automatique par nom de commerçant. Modifiez plusieurs transactions en lot. Gérez les étiquettes de catégories. Les règles font gagner du temps. Définissez-en une pour « Daily Grind → Café » et chaque future transaction Daily Grind se catégorise toute seule.</p>',
     '<p>त्वरित पहुँच के लिए महत्वपूर्ण लेनदेन चिह्नित करें। व्यापारी नाम से स्वचालित श्रेणीकरण नियम बनाएँ। कई लेनदेन बैच में संपादित करें। श्रेणी लेबल प्रबंधित करें। नियम समय बचाते हैं। «Daily Grind → Coffee» के लिए एक नियम सेट करें और हर भविष्य का Daily Grind लेनदेन अपने आप श्रेणीबद्ध होगा।</p>'),
    ('<h3>Accessibilité</h3>', '<h3>एक्सेसिबिलिटी</h3>'),
    ('<p>Mode sombre, mode contraste élevé et palettes adaptées aux daltoniens. Verrouillage de l\'application avec biométrie. Prise en charge du texte agrandi. Compatibilité complète avec les lecteurs d\'écran.</p>',
     '<p>डार्क मोड, उच्च कंट्रास्ट मोड और रंग अंधता-अनुकूल पैलेट। बायोमेट्रिक ऐप लॉक। बड़े टेक्स्ट समर्थन। पूर्ण स्क्रीन रीडर संगतता।</p>'),
    ('<h3>Fonctions de pleine conscience</h3>', '<h3>माइंडफुल फ़ीचर</h3>'),
    ('<p>La vue budget mindful retire les chiffres et affiche de simples anneaux de progression. Le mode coût en temps convertit les prix en heures de travail. Les étoiles PBJ gamifient l\'épargne. Les bilans bien-être suivent le stress financier. Le mode coût en temps ouvre les yeux. Il convertit chaque achat en heures de votre vie. Un dîner à 50 $ devient « 2,5 heures de travail ». Cela change votre façon de penser aux dépenses.</p>',
     '<p>माइंडफुल बजट दृश्य संख्याएँ हटाता है और सरल प्रगति रिंग दिखाता है। समय-लागत मोड कीमतों को काम के घंटों में बदलता है। PBJ स्टार बचत को गेमिफाई करते हैं। $50 का डिनर «2.5 घंटे का काम» बन जाता है।</p>'),
    ('<h3>Planification de la retraite</h3>', '<h3>सेवानिवृत्ति योजना</h3>'),
    ('<p>Suivez votre progression par rapport aux jalons d\'épargne Fidelity. Calculateur FIRE pour la retraite anticipée. Projections de taux de retrait sûr. Estimateur de revenu de retraite basé sur votre taux d\'épargne actuel.</p>',
     '<p>Fidelity बचत मील के पत्थर के सापेक्ष अपनी प्रगति ट्रैक करें। जल्दी सेवानिवृत्ति के लिए FIRE कैलकुलेटर। सुरक्षित निकासी दर अनुमान। आपकी वर्तमान बचत दर पर आधारित सेवानिवृत्ति आय अनुमानक।</p>'),
    ('<h3>Raccourcis vocaux</h3>', '<h3>वॉइस शॉर्टकट</h3>'),
    ('<p>Fonctionne avec Siri et Google Assistant. Six raccourcis intégrés : ajouter une transaction, vérifier le solde, statut du budget, et plus. Créez des raccourcis vocaux personnalisés pour vos actions les plus courantes.</p>',
     '<p>Siri और Google Assistant के साथ काम करता है। छह अंतर्निहित शॉर्टकट: लेनदेन जोड़ें, शेष जाँचें, बजट स्थिति, और अधिक। अपने सबसे सामान्य कार्यों के लिए कस्टम वॉइस शॉर्टकट बनाएँ।</p>'),
    ('<h3>Tarifs</h3>', '<h3>मूल्य निर्धारण</h3>'),
    ('<p>Commencez par un essai Premium de 15 jours — accès complet, sans carte. La synchronisation bancaire (États-Unis uniquement, via Teller) nécessite un abonnement Premium payant — pas pendant l\'essai. Ensuite, abonnez-vous mensuellement ou annuellement pour conserver l\'accès. Annulez à tout moment. Pas de publicité, pas de vente de données — votre abonnement est notre seule source de revenus.</p>',
     '<p>21-दिन के Premium ट्रायल से शुरू करें — पूर्ण पहुँच, बिना कार्ड। बैंक सिंक (केवल अमेरिका, Teller के माध्यम से) के लिए सशुल्क Premium सदस्यता चाहिए — ट्रायल के दौरान नहीं। फिर पहुँच बनाए रखने के लिए मासिक या वार्षिक सदस्यता लें। कभी भी रद्द करें। कोई विज्ञापन नहीं, डेटा बिक्री नहीं।</p>'),
    ('<h3>Confidentialité et sécurité</h3>', '<h3>गोपनीयता और सुरक्षा</h3>'),
    ('<p>Vos données restent dans le stockage privé de PocketBudJet sur votre appareil. Aucun identifiant bancaire n\'est jamais stocké. Les sauvegardes et la synchronisation cloud sont facultatives &mdash; chiffrement AES-256 avec une clé que vous seul connaissez. Verrouillage par code PIN ou biométrie disponible. La synchronisation bancaire optionnelle (États-Unis uniquement) passe par Teller sur Premium payant.</p>',
     '<p>आपका डेटा आपके डिवाइस पर PocketBudJet के निजी स्टोरेज में रहता है। कोई बैंक क्रेडेंशियल संग्रहीत नहीं होता। बैकअप और क्लाउड सिंक वैकल्पिक हैं &mdash; AES-256 एन्क्रिप्शन जिसकी कुंजी केवल आप जानते हैं। PIN या बायोमेट्रिक लॉक उपलब्ध। वैकल्पिक बैंक सिंक (केवल अमेरिका) सशुल्क Premium पर Teller के माध्यम से होता है।</p>'),
    ('<h3>Gestion des données et du stockage</h3>', '<h3>डेटा और स्टोरेज प्रबंधन</h3>'),
    ('<p>Définissez jusqu\'où votre sauvegarde conserve les détails complets des transactions, combien de mois de transactions restent sur votre téléphone pour un accès hors ligne instantané, et comment les images de reçus sont réparties entre l\'appareil et la sauvegarde. Appuyez sur Examiner et libérer de l\'espace pour prévisualiser exactement ce qui serait supprimé avant toute action. Les résumés annuels sont conservés définitivement — vos totaux année par année ne sont jamais supprimés.</p>',
     '<p>निर्धारित करें कि आपका बैकअप पूर्ण लेनदेन विवरण कितने समय तक रखता है, तत्काल ऑफ़लाइन पहुँच के लिए फ़ोन पर कितने महीने के लेनदेन रहते हैं, और रसीद छवियाँ कैसे विभाजित होती हैं। कार्रवाई से पहले क्या हटेगा यह देखने के लिए समीक्षा करें और स्थान खाली करें टैप करें। वार्षिक सारांश स्थायी रूप से रखे जाते हैं।</p>'),
    ('<h3>Besoin d\'aide ?</h3>', '<h3>सहायता चाहिए?</h3>'),
    ('<p>Écrivez à support@josspatech.com — nous répondons généralement sous 24 heures. Utilisez le formulaire de commentaires intégré pour signaler des bugs ou demander des fonctionnalités. Visitez <a href="/how-to/" style="color: #1A4F7A; font-weight: 600; text-decoration: underline;">josspatech.com/how-to</a> pour des guides vidéo sur l\'import de données, la configuration des budgets, le remboursement de dettes, la numérisation de reçus, et plus.</p>',
     '<p>support@josspatech.com पर लिखें — हम आमतौर पर 24 घंटे के भीतर जवाब देते हैं। बग रिपोर्ट या फ़ीचर अनुरोध के लिए इन-ऐप फ़ीडबैक फ़ॉर्म उपयोग करें। वीडियो गाइड के लिए <a href="/how-to/" style="color: #1A4F7A; font-weight: 600; text-decoration: underline;">josspatech.com/how-to</a> पर जाएँ।</p>'),
    ('title="Lecture/Pause"', 'title="चलाएँ/रोकें"'),
    ('<button class="chapter-btn active" data-slide="0">Premiers pas</button>',
     '<button class="chapter-btn active" data-slide="0">शुरुआत</button>'),
    ('<button class="chapter-btn" data-slide="1">Tableau de bord</button>',
     '<button class="chapter-btn" data-slide="1">डैशबोर्ड</button>'),
    ('<button class="chapter-btn" data-slide="2">Transactions</button>',
     '<button class="chapter-btn" data-slide="2">लेनदेन</button>'),
    ('<button class="chapter-btn" data-slide="3">Import</button>',
     '<button class="chapter-btn" data-slide="3">आयात</button>'),
    ('<button class="chapter-btn" data-slide="16">Import</button>',
     '<button class="chapter-btn" data-slide="16">आयात</button>'),
    ('<button class="chapter-btn" data-slide="4">Numérisation</button>',
     '<button class="chapter-btn" data-slide="4">स्कैनिंग</button>'),
    ('<button class="chapter-btn" data-slide="5">Budgets</button>',
     '<button class="chapter-btn" data-slide="5">बजट</button>'),
    ('<button class="chapter-btn" data-slide="6">Factures</button>',
     '<button class="chapter-btn" data-slide="6">बिल</button>'),
    ('<button class="chapter-btn" data-slide="7">Épargne</button>',
     '<button class="chapter-btn" data-slide="7">बचत</button>'),
    ('<button class="chapter-btn" data-slide="8">Dettes</button>',
     '<button class="chapter-btn" data-slide="8">कर्ज़</button>'),
    ('<button class="chapter-btn" data-slide="9">Investissements</button>',
     '<button class="chapter-btn" data-slide="9">निवेश</button>'),
    ('<button class="chapter-btn" data-slide="10">Rapports</button>',
     '<button class="chapter-btn" data-slide="10">रिपोर्ट</button>'),
    ('<button class="chapter-btn" data-slide="11">Coach IA</button>',
     '<button class="chapter-btn" data-slide="11">AI कोच</button>'),
    ('<button class="chapter-btn" data-slide="12">Assistant IA</button>',
     '<button class="chapter-btn" data-slide="12">AI सहायक</button>'),
    ('<button class="chapter-btn" data-slide="13">Recherche</button>',
     '<button class="chapter-btn" data-slide="13">खोज</button>'),
    ('<button class="chapter-btn" data-slide="14">Export</button>',
     '<button class="chapter-btn" data-slide="14">निर्यात</button>'),
    ('<button class="chapter-btn" data-slide="15">Tableau PC</button>',
     '<button class="chapter-btn" data-slide="15">PC डैशबोर्ड</button>'),
    ('<button class="chapter-btn" data-slide="17">Famille</button>',
     '<button class="chapter-btn" data-slide="17">परिवार</button>'),
    ('<button class="chapter-btn" data-slide="18">Calendrier</button>',
     '<button class="chapter-btn" data-slide="18">कैलेंडर</button>'),
    ('<button class="chapter-btn" data-slide="19">Règles</button>',
     '<button class="chapter-btn" data-slide="19">नियम</button>'),
    ('<button class="chapter-btn" data-slide="20">Accessibilité</button>',
     '<button class="chapter-btn" data-slide="20">एक्सेसिबिलिटी</button>'),
    ('<button class="chapter-btn" data-slide="21">Mindful</button>',
     '<button class="chapter-btn" data-slide="21">माइंडफुल</button>'),
    ('<button class="chapter-btn" data-slide="22">Retraite</button>',
     '<button class="chapter-btn" data-slide="22">सेवानिवृत्ति</button>'),
    ('<button class="chapter-btn" data-slide="23">Voix</button>',
     '<button class="chapter-btn" data-slide="23">आवाज़</button>'),
    ('<button class="chapter-btn" data-slide="24">Tarifs</button>',
     '<button class="chapter-btn" data-slide="24">मूल्य</button>'),
    ('<button class="chapter-btn" data-slide="25">Confidentialité</button>',
     '<button class="chapter-btn" data-slide="25">गोपनीयता</button>'),
    ('<button class="chapter-btn" data-slide="26">Données</button>',
     '<button class="chapter-btn" data-slide="26">डेटा</button>'),
    ('<button class="chapter-btn" data-slide="27">Aide</button>',
     '<button class="chapter-btn" data-slide="27">सहायता</button>'),
    ('<h2>La visite complète — 28 chapitres</h2>', '<h2>पूर्ण टूर — 28 अध्याय</h2>'),
    ('<h3>Premiers pas</h3>\n <p>Téléchargement, assistant, essai 15 jours</p>',
     '<h3>शुरुआत</h3>\n <p>डाउनलोड, विज़ार्ड, 21-दिन ट्रायल</p>'),
    ('<h3>Tableau de bord</h3>\n <p>Votre aperçu financier en un coup d\'œil</p>',
     '<h3>डैशबोर्ड</h3>\n <p>एक नज़र में आपका वित्तीय अवलोकन</p>'),
    ('<h3>Transactions</h3>\n <p>Suivre, rechercher et catégoriser chaque dollar</p>',
     '<h3>लेनदेन</h3>\n <p>हर डॉलर ट्रैक, खोज और श्रेणीबद्ध करें</p>'),
    ('<h3>Import</h3>\n <p>Relevés CSV, OFX, QFX, QIF, XLSX, PDF — sans connexion bancaire</p>',
     '<h3>आयात</h3>\n <p>CSV, OFX, QFX, QIF, XLSX, PDF स्टेटमेंट — बैंक लॉगिन के बिना</p>'),
    ('<h3>Numérisation</h3>\n <p>Appareil photo, scanner WiFi, OCR, écriture manuscrite</p>',
     '<h3>स्कैनिंग</h3>\n <p>कैमरा, WiFi स्कैनर, OCR, हस्तलिखित</p>'),
    ('<h3>Budgets</h3>\n <p>Modèles, limites personnalisées, suivi de progression</p>',
     '<h3>बजट</h3>\n <p>टेम्पलेट, कस्टम सीमाएँ, प्रगति ट्रैकिंग</p>'),
    ('<h3>Factures</h3>\n <p>Calendrier visuel et transactions récurrentes</p>',
     '<h3>बिल</h3>\n <p>दृश्य कैलेंडर और आवर्ती लेनदेन</p>'),
    ('<h3>Épargne</h3>\n <p>Objectifs, fonds de réserve, liste de souhaits, calculateur</p>',
     '<h3>बचत</h3>\n <p>लक्ष्य, सिंक फंड, इच्छा सूची, कैलकुलेटर</p>'),
    ('<h3>Dettes</h3>\n <p>Boule de neige ou avalanche avec date de libération</p>',
     '<h3>कर्ज़</h3>\n <p>स्नोबॉल या एवलांच मुक्ति तिथि के साथ</p>'),
    ('<h3>Investissements</h3>\n <p>Actions, crypto, immobilier, score de crédit</p>',
     '<h3>निवेश</h3>\n <p>स्टॉक, क्रिप्टो, संपत्ति, क्रेडिट स्कोर</p>'),
    ('<h3>Rapports</h3>\n <p>Plus de 10 types de rapports et rapports personnalisés</p>',
     '<h3>रिपोर्ट</h3>\n <p>10+ रिपोर्ट प्रकार और कस्टम रिपोर्ट</p>'),
    ('<h3>Coach IA</h3>\n <p>Analyses personnalisées et récapitulatifs hebdomadaires</p>',
     '<h3>AI कोच</h3>\n <p>व्यक्तिगत अंतर्दृष्टि और साप्ताहिक सारांश</p>'),
    ('<h3>Assistant IA</h3>\n <p>Posez des questions en langage courant</p>',
     '<h3>AI सहायक</h3>\n <p>सामान्य भाषा में प्रश्न पूछें</p>'),
    ('<h3>Recherche</h3>\n <p>Trouvez transactions et fonctions instantanément</p>',
     '<h3>खोज</h3>\n <p>लेनदेन और फ़ीचर तुरंत खोजें</p>'),
    ('<h3>Export</h3>\n <p>Six formats plus sauvegarde chiffrée</p>',
     '<h3>निर्यात</h3>\n <p>छह प्रारूप और एन्क्रिप्टेड बैकअप</p>'),
    ('<h3>Tableau PC</h3>\n <p>Accès navigateur sur le réseau local</p>',
     '<h3>PC डैशबोर्ड</h3>\n <p>स्थानीय नेटवर्क पर ब्राउज़र पहुँच</p>'),
    ('<h3>Famille</h3>\n <p>Synchronisation WiFi ou Bluetooth en famille</p>',
     '<h3>परिवार</h3>\n <p>WiFi या Bluetooth पारिवारिक सिंक</p>'),
    ('<h3>Calendrier</h3>\n <p>Vue mensuelle avec points de transaction et échéances</p>',
     '<h3>कैलेंडर</h3>\n <p>लेनदेन बिंदुओं और नियत तारीखों के साथ मासिक दृश्य</p>'),
    ('<h3>Règles</h3>\n <p>Catégorisation automatique et modification en lot</p>',
     '<h3>नियम</h3>\n <p>स्वचालित श्रेणीकरण और बैच संपादन</p>'),
    ('<h3>Accessibilité</h3>\n <p>Mode sombre, palettes daltoniennes, lecteur d\'écran</p>',
     '<h3>एक्सेसिबिलिटी</h3>\n <p>डार्क मोड, रंग अंधता पैलेट, स्क्रीन रीडर</p>'),
    ('<h3>Mindful</h3>\n <p>Mode coût en temps et bilans bien-être</p>',
     '<h3>माइंडफुल</h3>\n <p>समय-लागत मोड और कल्याण चेक-इन</p>'),
    ('<h3>Retraite</h3>\n <p>Calculateur FIRE et suivi des jalons</p>',
     '<h3>सेवानिवृत्ति</h3>\n <p>FIRE कैलकुलेटर और मील के पत्थर ट्रैकिंग</p>'),
    ('<h3>Voix</h3>\n <p>Raccourcis Siri et Google Assistant</p>',
     '<h3>आवाज़</h3>\n <p>Siri और Google Assistant शॉर्टकट</p>'),
    ('<h3>Tarifs</h3>\n <p>Essai 15 jours, puis mensuel ou annuel ; sync bancaire US = Premium payant</p>',
     '<h3>मूल्य</h3>\n <p>21-दिन ट्रायल, फिर मासिक या वार्षिक; US बैंक सिंक = सशुल्क Premium</p>'),
    ('<h3>Confidentialité</h3>\n <p>Chiffrement sur l\'appareil, cloud facultatif</p>',
     '<h3>गोपनीयता</h3>\n <p>डिवाइस पर एन्क्रिप्शन, वैकल्पिक क्लाउड</p>'),
    ('<h3>Données et stockage</h3>\n <p>Rétention des sauvegardes, historique local, niveaux de reçus</p>',
     '<h3>डेटा और स्टोरेज</h3>\n <p>बैकअप प्रतिधारण, स्थानीय इतिहास, रसीद स्तर</p>'),
    ('<h3>Aide</h3>\n <p>Support par courriel et commentaires intégrés</p>',
     '<h3>सहायता</h3>\n <p>ईमेल सहायता और इन-ऐप फ़ीडबैक</p>'),
    ('<h2>Prêt à reprendre le contrôle de vos finances ?</h2>',
     '<h2>अपने वित्त पर नियंत्रण लेने के लिए तैयार?</h2>'),
    ('<p>Téléchargez PocketBudJet dès aujourd\'hui et commencez avec la visite du guide utilisateur complet intégrée à l\'application.</p>',
     '<p>आज ही PocketBudJet डाउनलोड करें और ऐप में अंतर्निहित पूर्ण उपयोगकर्ता गाइड टूर से शुरू करें।</p>'),
    ('<a href="#" class="download-button">Télécharger</a>', '<a href="#" class="download-button">डाउनलोड</a>'),
    ('<a href="/">Accueil</a> | <a href="/#products">Produits</a>',
     '<a href="/">होम</a> | <a href="/#products">उत्पाद</a>'),
    ('voiceBtn.title = \'Activer/désactiver la narration vocale\';',
     'voiceBtn.title = \'ध्वनि कथन चालू/बंद करें\';'),
    ('voiceBtn.setAttribute(\'aria-label\', \'Activer/désactiver la narration vocale\');',
     'voiceBtn.setAttribute(\'aria-label\', \'ध्वनि कथन चालू/बंद करें\');'),
    ('// MP3 audio: EN narration reused until FR re-voice (edge-tts fr-FR-*) ships',
     '// MP3 audio: EN narration reused until HI re-voice (edge-tts hi-IN-*) ships'),
]

SEARCH_HI = (
    '<p>PocketBudJet में दर्जनों फ़ीचर हैं — बेतरतीब ब्राउज़ करके सभी नहीं मिलेंगे। '
    'राशि या व्यापारी से लेनदेन खोजें। फ़ीचर खोजें: यात्रा ट्रैकिंग के लिए «mileage», '
    'वॉइस शॉर्टकट के लिए «voice», प्लानर के लिए «retirement» या एक्सेसिबिलिटी के लिए '
    '«colorblind» आज़माएँ। अगर सोचें कि PBJ कुछ कर सकता है, खोजें।</p>'
)


def main():
    text = FR.read_text(encoding='utf-8')
    for old, new in REPLACEMENTS:
        if old not in text:
            raise SystemExit(f'Missing expected fragment: {old[:80]!r}')
        text = text.replace(old, new, 1)

    text, n = re.subn(
        r'(<h3>कोई भी फ़ीचर तुरंत खोजें</h3>\s*)<p>.*?</p>',
        r'\1' + SEARCH_HI,
        text,
        count=1,
        flags=re.DOTALL,
    )
    if n != 1:
        raise SystemExit('Search-feature narration paragraph replace failed')

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text, encoding='utf-8')
    print(f'Wrote {OUT}')


if __name__ == '__main__':
    main()
